apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.2.1
        command: ["bash -c 'if [ ! -f /mnt/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /mnt/update_run.sh && /etc/confluent/docker/run ; fi'"]
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "'PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092'"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_JMX_PORT
            value: "9997"
          - name: KAFKA_JMX_HOSTNAME
            value: "localhost"
          - name: KAFKA_JMX_OPTS
            value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997"
          - name: KAFKA_PROCESS_ROLES
            value: "'broker,controller'"
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "'1@kafka0:29093'"
          - name: KAFKA_LISTENERS
            value: "'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "'PLAINTEXT'"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "'CONTROLLER'"
          - name: KAFKA_LOG_DIRS
            value: "'/tmp/kraft-combined-logs'"        
        volumeMounts:
        - mountPath: /mnt
          name: kafka-volume
        ports:
          - containerPort: 9997
            name: metrics
          - containerPort: 9092
      volumes:
      - name: kafka-volume
        hostPath:
          # directory location on host
          path: /scripts/
          # this field is optional
          type: Directory

---

kind: Service
apiVersion: v1
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - port: 9997
    - port: 9092