apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaUI
  labels:
    app: kafkaUI
spec:
  selector:
    matchLabels:
      app: kafkaUI
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafkaUI
    spec:
      containers:
      - name: kafkaUI
        image: provectuslabs/kafka-ui
        ports:
          - containerPort: 8080
        env:
          KAFKA_CLUSTERS_0_NAME: local
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
          KAFKA_CLUSTERS_0_METRICS_PORT: 9997
          KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
          KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
          KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083

---

kind: Service
apiVersion: v1
metadata:
  name: kafkaUI-service
spec:
  selector:
    app: kafkaUI
  ports:
    - port: 8080