apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaUI
  labels:
    app: kafkaUI
spec:
  selector:
    matchLabels:
      app: kafkaUI
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafkaUI
    spec:
      containers:
      - name: kafkaUI
        image: provectuslabs/kafka-ui
        ports:
          - containerPort: 8080
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "local"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka0:29092"
          - name: KAFKA_CLUSTERS_0_METRICS_PORT
            value: "9997"
          - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
            value: "http://schemaregistry0:8085"
          - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
            value: "first"
          - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
            value: "http://kafka-connect0:8083"

---

kind: Service
apiVersion: v1
metadata:
  name: kafkaui-service
spec:
  selector:
    app: kafkaUI
  ports:
    - port: 8080